version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    cap_add:
      - CAP_NET_ADMIN
    volumes:
      - ${PWD}:/src
      - ${HOME}/.cache/go-build:/go/pkg/mod
    working_dir: /src
    environment:
      - GOCACHE=/go/pkg/mod
